### ISSUE TITLE
Feature: User can search a keyword or phrase associated with objects on view at The Met

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search a keyword or phrase associated with objects on view at The Met.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can type a keyword or phrase associated with objects on view at The Met in the search bar. Once the keyword or phrase is submitted, the search bar will clear and reset. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![User can search a keyword or phrase figma wireframe](https://user-images.githubusercontent.com/85596835/148271812-22b97d3e-6092-4683-9434-10912adb449c.png)
![User can search a keyword 1-3 or phrase desktop figma wireframe](https://user-images.githubusercontent.com/85596835/148271949-91f25738-c759-407a-9142-6a1d7109728a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div` element with a `data-view` attribute and value of `"search-form"` to the HTML.
- [x] Add a form and search bar to the `div` element.
- [x] Make search input required.
- [x] Outline the search bar input in Met red when in focus.
- [x] Listen for `'submit'` event on the form and:
  - [x] Save the input value to a variable.
  - [x] Reset the form to clear the search input.
- [x] Create an empty array to store Met object IDs.
- [x] Create a `getObjectIds` function to:
  - [x] Create a `new XMLHttpRequest()` object and save it to a varaible.
  - [x] `open()` the object to send a `'GET'` request to The Met museum's API with `query` parameter value set to input value variable, and `isOnView` parameter value set to `true`.
  - [x] Assign response type to `'json'`.
  - [x] Listen for `'load'` event and add the `reponse`'s `objectIDs` property value to the Met object IDs array.
  - [x] Call the `send()` method of the object.
- [x] Add and call the `getObjectIds` function in the `"submit"` event handler.
- [x] Make sure that the Met object IDs array contains the appropriate number of object IDs compared to those returned in Ajax response.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Confirm that all functionality still works and design maintains appearance in a private browsing session. 
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
