### ISSUE TITLE
Feature: User can view a list of four random objects returned from the searched keyword

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

After searching a keyword or phrase, the user can view a list of four random objects returned from the searched keyword, including:
- Object image 
- Object title
- Artist Name
- Object medium
- Gallery Number in which it's on view
- A button linked to the object’s webpage on The Met’s website

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user submits a search, the user will see the "Discoveries" page which contains a list of four random objects returned from the user's search and some of the object's information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![User can view list of 4 randomized objects figma wireframe](https://user-images.githubusercontent.com/85596835/149275715-90cc58a2-40ec-4966-a75d-3d8d290933fd.png)
![User can view list of 4 randomized objects desktop figma wireframe](https://user-images.githubusercontent.com/85596835/148125784-324628fd-8342-4f44-8040-44dddeaceeb0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div` with a `data-view` attribute with a value of `"discoveries"` to the HTML.
- [x] Add an empty unordered list to the 'div' element.
- [x] Add a few test museum objects as line items to the list and style to match wireframe appearance. 
- [x] Verify that the appearance matches the wireframe in both mobile and desktop views.  
- [x] Create a data model with the following properties: `view: 'search-form', searchObjects: [], saved: [], nextObjId: 1`.
- [x] Create an empty array to store four random museum object IDs from the Met object IDs array.
- [x] Create an empty array to store the four random museum objects and their information.
- [x] Define a `randomize` function that selects four random museum object IDs from the Met object IDs array and adds those IDs to the empty storage array. 
- [x]  Define a `getObjectInfo` function that:
  - [x] Create a `new XMLHttpRequest()` object and save it to a varaible.
  - [x] `open()` the object to send a 'GET' request to The Met museum's API with the `objectID` parameter value set to the randomized museum object ID, and assign the response type to `'json'`.
  - [x] Listen for `load` event and add the following data from the `response` to a new object literal:
    - Object image absolute URL
    - Object title
    - Artist Name
    - Object medium
    - Gallery Number in which it's on view
    - Absolute URL to the object’s webpage on The Met’s website
  - [x] Make sure that the created object literal contains the appropriate information compared to the Ajax responses. 
  - [x] Add the object literal to the museum object information array.
  - [x] Add the object literal to the `searchObjects' property of the data model.
- [x] Loop through the storage array and call the `getObjectInfo` function for each item in the array.
- [x] Add loop,  `randomize`, and `getObjectInfo`  functions to the `'submit'` event handler.
- [x] Verify the four randomized museum objects are saved to the data model and the museum object information array.
- [x] Define a function that takes a randomized museum object and returns a DOM tree that matches one of the test museum object examples in the HTML. 
- [x] Use a loop to create a DOM tree for each of the four randomized museum objects in the data model and append it to the page `ul` when the `'DOMContentLoaded'` event is fired. 
- [x] Remove test examples from the HTML once the randomized museum objects are successfully being appended to the DOM on page load.
- [x] Verify that searching keyword or phrase creates a DOM tree for all four randomized objects and adds them to the page. 
- [x] Verify that searching keyword or phrase automatically shows the `'discoveries'` view without reloading the page. 
- [x] Verify that refreshing the page shows the same view as before refreshing.
- [x] Add an anchor to the palette icon and "Discover" elements in the header to show the search form and hide the "Discoveries" view. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
