### ISSUE TITLE
Feature: User can add returned objects to their Must-See List

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add and save returned objects of their choosing to their Must-See List.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add and save any of the four randomized objects to their Must-See List by clicking on the plus sign icon on the object's listing card. Once the plus sign icon is clicked, it will change to a checkmark icon confirming it was added. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![User can add and save objects to Must-See List - Mobile figma](https://user-images.githubusercontent.com/85596835/150837040-1d2f7c25-7272-4862-a60b-6e6c8ab9ba96.png)
![Add and Save Objects to Must-See List - Desktop Figma](https://user-images.githubusercontent.com/85596835/150836800-6577f1b0-6555-491f-b8bf-f0e6db8b92da.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div` with a 'data-view' attribute with a value of `"must-see"` to the HTML.
- [x] Add an empty unordered list to the `div` element.
- [x] Edit the `'searchEventHandler'` function to begin every search with empty  `'objIdArr'`, `'randomObjIds'`, `'randomObjInfo'` arrays and an empty `'search'` property in the data model.
- [x] Ensure that only the current search objects are appended to the DOM.
- [x] Listen for clicks on the discoveries `ul` and if the plus icon on search results is clicked:
  - [x] Replace the plus icon with a checkmark icon indicating the object has been added.
  - [x] Add the `nextObjId` to the object's information.
  - [x] Increment the `nextObjId` on the data model.
  - [x] Prepend the object information to the `'saved'` property of the data model.
  - [x] Ensure that the checkmark icon remains on the search object on page reload.
- [x] Verify that the item's object literal is saving to the `'saved'` property of the data model with the correct `'nextObjId'`
- [x] Verify that the appearance matches the wireframe in both mobile and desktop views.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
