### ISSUE TITLE
Feature: User can view their Must-See List and mark an object as seen

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their Must-See List by clicking on the list icon in the navbar, and the user can mark an object as seen. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view their Must-See List by clicking on the list icon in the navbar. On the "Must-See List" page, the user can mark an object as seen by clicking on the eye-prohibition icon. Once clicked, the icon will change color to Met blue and the prohibition sign will be removed. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Correct User Can View (1)](https://github.com/llaveirge/ajax-project/assets/85596835/066ef20e-eb7a-45f8-a41a-17a572eb4e75)

![View Must-See List and Mark As Seem Desktop](https://github.com/llaveirge/ajax-project/assets/85596835/6723af46-7c6a-43d9-9e2d-7d34a1a28bfe)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a few test museum objects as line items to the `#must-see-list` `ul` and style to match wireframe appearance.
- [x] Define a function that returns a DOM tree for each saved object that matches one of the test museum object examples. 
- [x] Use a loop to create a DOM tree for each saved search object in the data model and append to the page `ul` when the `'DOMContentLoaded'` event is fired.
- [x] Ensure that each rendered object is given a `data-obj-id` attribute associated with the `'nextObjId'`
- [x] Verify that each item saved is added to the "Must-See" list without refreshing the page. 
- [x] Remove the test objects once the objects are successfully saved and appended to the "Must-See" list.
- [x] Define a function that toggles the  'seen' property of the 'randomObject' objects in the 'saved' array of the data model when the eye/eye prohibition icons are clicked on the objects in the 'Must-See' list, and when toggled, ensure that the grey prohibition icon is replaced by the 'Met blue' eye icon, indicating the user has seen the piece, or that the eye icon is replaced by the grey eye-prohibition icon, indicating the user has not seen the piece.
- [x] Put the prohibition eye/eye icon in a button element so that the pointer renders properly
- [x] Ensure that if the eye icon is clicked again, it changed back to the grey prohibition eye icon.
- [x] Add a message to the `must-see` page if there are no saved works indicating there is nothing to show to the user.
- [x] Add an anchor to the list icon in the header to show the "Must-See" list and hide the form and the "Discoveries" view.
- [x] Add a hash change function to handle hash changes in the URL bar to show the appropriate page views.
- [x] Verify that the appearance matches the wireframe in both mobile and desktop views.
- [x] Verify that refreshing the page shows the same view as before refreshing.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that all functionality still works and design maintains appearance in a private browsing session.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
