### ISSUE TITLE
Feature: User can remove objects from their Must-See List

### ISSUE THREAD

**Issue by llaveirge** [llaveirge/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove objects from their Must-See List by clicking on the trashcan icon.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can remove unwanted or seen objects from their Must-See List by clicking on the trashcan icon on the object's listing card. Once the trashcan icon is clicked, the user will be prompted to confirm the object's removal or to cancel the removal. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![User can remove objects from Must-See List figma wireframe](https://user-images.githubusercontent.com/85596835/148135317-6da06fc8-e7ac-4927-b6f9-2c2c75d91cff.png)
![User can remove objects from Must-See List desktop figma wireframe](https://user-images.githubusercontent.com/85596835/148135335-e216860a-3042-4bcc-ba47-4f050f8b797e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a sibling `<div>` element with an `id` attribute with a value of "modal-container". 
- [x] Add styling to the `modal-container` `<div>` so that the background is shaded in MET dark gray with 75% opacity to match the wireframe.
- [x] Create a child `<div>` element of the `modal-container` `<div>` with an `id` attribute with a value of "remove-modal".
- [x] Within the `remove-modal` `<div>`, add the confirmation message with styling matching the wireframes. 
- [x] Create a child `<div>` element of the `remove-modal` `<div>` element with an `id` attribute of "button-container". 
- [x] Within the `button-container` `<div>` add two `<button>` elements with appropriate `id` and `type` attributes.
- [x] Style the two `<button>` elements to match the wireframes.
- [x] Wrap the existing trashcan icon in a `<button>` element. 
- [x] Update the CSS rule set for the trashcan icon so that color of the icon changes to MET red when hovered and focused.
- [x] Define a function named `toggleModal` that toggles the visibility of the `modal-container` `<div>` and all child elements.
- [x] Verify that the `toggleModal` function works properly. 
- [x] Listen for clicks on the trashcan icon `<button>` element, and when clicked: 
  - [x] Call the `toggleModal` function so that the modal is visible.
- [x] Define a function named `removeSavedObj` that when called:
  - [x] Removes the associated object from the `saved` array within the `data` model object.
  - [x] Dynamically updates the `DOM` tree and removes the saved object's `<li>` element from the `must-see-list` `<ul>` element.
- [x] Verify that the `removeSavedObj` function works properly.
- [x] Listen for clicks on the `remove` `<button>` inside the modal, and when clicked:
  - [x] Calls the `removedSavedObj` function and removes the saved object from the 'Must-See List'.
  - [x] Calls the `toggleModal` function and closes the modal. 
- [x] Listen for clicks on the `cancel` `<button>` inside the modal, and when clicked:
  - [x] Calls the `toggleModal` function and closes the modal without altering the 'Must-See List'.
- [ ] Verify that if all objects are removed from the 'Must-See List', the empty 'Li' message appears. 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure all click targets show a `cursor: pointer` when hovering with the mouse.
- [ ] Verify that the appearance matches the wireframe in both mobile and desktop views.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Remove all commented-out code.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
